@startuml
left to right direction
actor :new Actor:
usecase "Identificarse" as login
usecase "Pagar" as pago
usecase "Elegir mensajero" as mensajero
usecase "Confirmar" as confirmar
usecase "Registrarse" as registro
usecase "Pagar con tarjeta" as pagotarjeta
usecase "Pagar con transferencia" as pagotransferencia
:new Actor: -- login
:new Actor: -- pago
:new Actor: -- mensajero
:new Actor: -- confirmar
login <.. registro:<<extend>>
pago <|-- pagotarjeta
pago <|--pagotransferencia
@enduml